// components/DrawingCanvas.tsx
import React, { useRef, useEffect, useImperativeHandle, forwardRef, useState } from 'react';

export interface DrawingCanvasRef {
  clearCanvas: () => void;
}

const DrawingCanvas = forwardRef<DrawingCanvasRef, {}>((props, ref) => {
    const canvasRef = useRef<HTMLCanvasElement>(null);
    const contextRef = useRef<CanvasRenderingContext2D | null>(null);
    const [isDrawing, setIsDrawing] = useState(false);

    useEffect(() => {
        const canvas = canvasRef.current;
        if (!canvas) return;
        
        const parent = canvas.parentElement;
        if (!parent) return;

        const setCanvasSize = () => {
            const { width } = parent.getBoundingClientRect();
            canvas.width = width * 2; // for retina display
            canvas.height = (width / 2) * 2; // 2:1 aspect ratio
            canvas.style.width = `${width}px`;
            canvas.style.height = `${width / 2}px`;

            const context = canvas.getContext('2d');
            if (context) {
                context.scale(2, 2);
                context.lineCap = 'round';
                context.strokeStyle = '#E4E4E7'; // zinc-200
                context.lineWidth = 4;
                contextRef.current = context;
            }
        };

        setCanvasSize();

        const resizeObserver = new ResizeObserver(setCanvasSize);
        resizeObserver.observe(parent);

        return () => resizeObserver.unobserve(parent);

    }, []);

    const getCoords = (event: MouseEvent | Touch) => {
        const canvas = canvasRef.current;
        if (!canvas) return { offsetX: 0, offsetY: 0 };
        const rect = canvas.getBoundingClientRect();
        const clientX = 'clientX' in event ? event.clientX : 0;
        const clientY = 'clientY' in event ? event.clientY : 0;
        return {
          offsetX: clientX - rect.left,
          offsetY: clientY - rect.top
        };
    };

    const startDrawing = (e: React.MouseEvent | React.TouchEvent) => {
        const nativeEvent = e.nativeEvent;
        const event = 'touches' in nativeEvent ? nativeEvent.touches[0] : nativeEvent;
        if (!event) return;
        const { offsetX, offsetY } = getCoords(event);
        contextRef.current?.beginPath();
        contextRef.current?.moveTo(offsetX, offsetY);
        setIsDrawing(true);
    };

    const finishDrawing = () => {
        contextRef.current?.closePath();
        setIsDrawing(false);
    };

    const draw = (e: React.MouseEvent | React.TouchEvent) => {
        if (!isDrawing) return;
        const nativeEvent = e.nativeEvent;
        const event = 'touches' in nativeEvent ? nativeEvent.touches[0] : nativeEvent;
        if (!event) return;
        const { offsetX, offsetY } = getCoords(event);
        contextRef.current?.lineTo(offsetX, offsetY);
        contextRef.current?.stroke();
    };

    useImperativeHandle(ref, () => ({
        clearCanvas() {
            const canvas = canvasRef.current;
            const context = contextRef.current;
            if (canvas && context) {
                context.clearRect(0, 0, canvas.width, canvas.height);
            }
        }
    }));
    
    return (
        <div className="w-full flex flex-col items-center gap-2">
            <div className="flex justify-end w-full">
                <button
                    onClick={() => ref && 'current' in ref && ref.current?.clearCanvas()}
                    className="flex items-center text-sm font-medium py-1 px-3 rounded-lg transition-colors bg-zinc-700/50 hover:bg-zinc-700/80 text-zinc-300"
                    aria-label="Zeichenbereich leeren"
                >
                    <span className="material-symbols-outlined mr-1 text-base">delete_sweep</span>
                    <span>Leeren</span>
                </button>
            </div>
            <canvas
                ref={canvasRef}
                onMouseDown={startDrawing}
                onMouseUp={finishDrawing}
                onMouseMove={draw}
                onMouseLeave={finishDrawing}
                onTouchStart={startDrawing}
                onTouchEnd={finishDrawing}
                onTouchMove={draw}
                className="bg-zinc-800 rounded-lg cursor-crosshair"
            />
        </div>
    );
});

export default DrawingCanvas;

// src/app/features/flashcards/components/drawing-canvas/drawing-canvas.component.ts
import { Component, ElementRef, ViewChild, AfterViewInit, OnDestroy, output } from '@angular/core';

@Component({
    selector: 'app-drawing-canvas',
    standalone: true,
    templateUrl: './drawing-canvas.component.html'
})
export class DrawingCanvasComponent implements AfterViewInit, OnDestroy {
    @ViewChild('canvas') canvasRef!: ElementRef<HTMLCanvasElement>;

    cleared = output<void>();

    private ctx: CanvasRenderingContext2D | null = null;
    private isDrawing = false;
    private lastX = 0;
    private lastY = 0;

    private boundTouchStart = this.handleTouchStart.bind(this);
    private boundTouchMove = this.handleTouchMove.bind(this);
    private boundTouchEnd = this.handleTouchEnd.bind(this);

    ngAfterViewInit(): void {
        this.initCanvas();
    }

    ngOnDestroy(): void {
        this.removeCanvasListeners();
    }

    private initCanvas(): void {
        if (!this.canvasRef?.nativeElement) return;
        const canvas = this.canvasRef.nativeElement;
        this.ctx = canvas.getContext('2d');

        if (this.ctx) {
            this.ctx.strokeStyle = '#e4e4e7';
            this.ctx.lineWidth = 5;
            this.ctx.lineCap = 'round';
            this.ctx.lineJoin = 'round';
        }

        canvas.addEventListener('touchstart', this.boundTouchStart, { passive: false });
        canvas.addEventListener('touchmove', this.boundTouchMove, { passive: false });
        canvas.addEventListener('touchend', this.boundTouchEnd, { passive: false });
    }

    private removeCanvasListeners(): void {
        if (!this.canvasRef?.nativeElement) return;
        const canvas = this.canvasRef.nativeElement;
        canvas.removeEventListener('touchstart', this.boundTouchStart);
        canvas.removeEventListener('touchmove', this.boundTouchMove);
        canvas.removeEventListener('touchend', this.boundTouchEnd);
    }

    // Mouse events
    onMouseDown(event: MouseEvent): void {
        this.isDrawing = true;
        const canvas = this.canvasRef.nativeElement;
        const rect = canvas.getBoundingClientRect();
        const scaleX = canvas.width / rect.width;
        const scaleY = canvas.height / rect.height;
        this.lastX = (event.clientX - rect.left) * scaleX;
        this.lastY = (event.clientY - rect.top) * scaleY;
    }

    onMouseMove(event: MouseEvent): void {
        if (!this.isDrawing || !this.ctx) return;
        const canvas = this.canvasRef.nativeElement;
        const rect = canvas.getBoundingClientRect();
        const scaleX = canvas.width / rect.width;
        const scaleY = canvas.height / rect.height;
        const x = (event.clientX - rect.left) * scaleX;
        const y = (event.clientY - rect.top) * scaleY;

        this.ctx.beginPath();
        this.ctx.moveTo(this.lastX, this.lastY);
        this.ctx.lineTo(x, y);
        this.ctx.stroke();

        this.lastX = x;
        this.lastY = y;
    }

    onMouseUp(): void {
        this.isDrawing = false;
    }

    onMouseLeave(): void {
        this.isDrawing = false;
    }

    // Touch events
    private handleTouchStart(event: TouchEvent): void {
        event.preventDefault();
        if (event.touches.length !== 1) return;

        this.isDrawing = true;
        const touch = event.touches[0];
        const canvas = this.canvasRef.nativeElement;
        const rect = canvas.getBoundingClientRect();
        const scaleX = canvas.width / rect.width;
        const scaleY = canvas.height / rect.height;
        this.lastX = (touch.clientX - rect.left) * scaleX;
        this.lastY = (touch.clientY - rect.top) * scaleY;
    }

    private handleTouchMove(event: TouchEvent): void {
        event.preventDefault();
        if (!this.isDrawing || !this.ctx || event.touches.length !== 1) return;

        const touch = event.touches[0];
        const canvas = this.canvasRef.nativeElement;
        const rect = canvas.getBoundingClientRect();
        const scaleX = canvas.width / rect.width;
        const scaleY = canvas.height / rect.height;
        const x = (touch.clientX - rect.left) * scaleX;
        const y = (touch.clientY - rect.top) * scaleY;

        this.ctx.beginPath();
        this.ctx.moveTo(this.lastX, this.lastY);
        this.ctx.lineTo(x, y);
        this.ctx.stroke();

        this.lastX = x;
        this.lastY = y;
    }

    private handleTouchEnd(event: TouchEvent): void {
        event.preventDefault();
        this.isDrawing = false;
    }

    // Public method to clear the canvas
    clear(): void {
        if (!this.ctx || !this.canvasRef?.nativeElement) return;
        const canvas = this.canvasRef.nativeElement;
        this.ctx.clearRect(0, 0, canvas.width, canvas.height);
        this.cleared.emit();
    }
}

<div class="flex flex-col gap-2">
    <div class="flex items-center justify-between">
        <span class="text-xs text-dash-text-dim uppercase tracking-wider flex items-center gap-1">
            <span class="material-symbols-sharp text-sm">draw</span>
            Zeichenbereich
        </span>
        <button (click)="clear()"
            class="px-3 py-1 bg-dash-bg hover:bg-dash-accent rounded-sm text-xs text-dash-text-dim hover:text-white transition-all flex items-center gap-1">
            <span class="material-symbols-sharp text-sm">delete</span>
            Löschen
        </button>
    </div>
    <div class="border border-dash-border rounded-sm overflow-hidden">
        <canvas #canvas width="900" height="500" class="w-full cursor-crosshair touch-none canvas-dotted"
            (mousedown)="onMouseDown($event)" (mousemove)="onMouseMove($event)" (mouseup)="onMouseUp()"
            (mouseleave)="onMouseLeave()">
        </canvas>
    </div>
</div>
