// src/app/features/flashcards/components/modals/settings-modal/settings-modal.component.ts
import { Component, input, output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Deck } from '../../../flashcard.model';

@Component({
    selector: 'app-settings-modal',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './settings-modal.component.html'
})
export class SettingsModalComponent {
    decks = input.required<Deck[]>();

    closed = output<void>();
    openImport = output<void>();
    exportCards = output<string>();
    clearAll = output<void>();

    exportDeckId = signal('');

    close(): void {
        this.closed.emit();
    }

    onOpenImport(): void {
        this.openImport.emit();
    }

    onExport(): void {
        this.exportCards.emit(this.exportDeckId());
    }

    onClearAll(): void {
        this.clearAll.emit();
    }
}

<div class="fixed inset-0 z-50 flex items-center justify-center p-4">
    <div class="absolute inset-0 bg-black/60 backdrop-blur-sm" (click)="close()"></div>
    <div class="relative gradient-card p-6 rounded-sm shadow-2xl w-full max-w-md flex flex-col gap-4 accent-glow">
        <div class="flex items-center justify-between">
            <h2 class="text-lg font-bold text-dash-text">Flashcard Einstellungen</h2>
            <button (click)="close()" class="text-dash-text-dim hover:text-white transition-colors">
                <span class="material-symbols-sharp">close</span>
            </button>
        </div>

        <div class="flex flex-col gap-3">
            <div class="space-y-1">
                <label class="text-xs text-dash-text-dim uppercase font-bold tracking-wider">Export Quelle</label>
                <select [ngModel]="exportDeckId()" (ngModelChange)="exportDeckId.set($event)"
                    class="w-full bg-dash-bg border border-dash-border text-dash-text p-2 rounded-sm text-sm focus:outline-none focus:border-dash-accent transition-colors">
                    <option value="">Alle geladenen Karten</option>
                    @for (deck of decks(); track deck.id) {
                    <option [value]="deck.id">{{ deck.name }}</option>
                    }
                </select>
            </div>

            <button (click)="onExport()"
                class="flex items-center gap-3 p-3 bg-dash-bg hover:bg-dash-accent rounded-sm text-dash-text-dim hover:text-white transition-colors text-left">
                <span class="material-symbols-sharp">download</span>
                <div class="flex flex-col">
                    <span class="font-bold text-sm">Export Karten</span>
                    <span class="text-xs opacity-70">Download als .txt (Front;Back)</span>
                </div>
            </button>

            <button (click)="onOpenImport()"
                class="flex items-center gap-3 p-3 bg-dash-bg hover:bg-dash-accent rounded-sm text-dash-text-dim hover:text-white transition-colors text-left">
                <span class="material-symbols-sharp">upload</span>
                <div class="flex flex-col">
                    <span class="font-bold text-sm">Import Karten</span>
                    <span class="text-xs opacity-70">Text-Format importieren</span>
                </div>
            </button>

            <div class="border-t border-dash-border my-2"></div>

            <button (click)="onClearAll()"
                class="flex items-center gap-3 p-3 bg-dash-bg hover:bg-red-600 rounded-sm text-dash-text-dim hover:text-white transition-colors text-left">
                <span class="material-symbols-sharp">delete_forever</span>
                <div class="flex flex-col">
                    <span class="font-bold text-sm">Alle Karten löschen</span>
                    <span class="text-xs opacity-70">Permanent entfernen</span>
                </div>
            </button>
        </div>
    </div>
</div>

// components/SettingsModal.tsx
import React from 'react';

interface SettingsModalProps {
    isOpen: boolean;
    onClose: () => void;
    isEditing: boolean;
    onToggleEditing: () => void;
    onImport: () => void;
    onExport: () => void;
    onShowCredits: () => void;
}

export const SettingsModal: React.FC<SettingsModalProps> = ({
    isOpen,
    onClose,
    isEditing,
    onToggleEditing,
    onImport,
    onExport,
    onShowCredits,
}) => {
    if (!isOpen) return null;

    return (
        <div
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={onClose}
        >
            <div
                className="w-full max-w-sm bg-slate-800/90 backdrop-blur-xl border border-white/10 rounded-xl shadow-2xl p-6"
                onClick={(e) => e.stopPropagation()}
            >
                <div className="flex justify-between items-center mb-6">
                    <h2 className="text-xl font-bold text-white">Einstellungen</h2>
                    <button
                        onClick={onClose}
                        className="text-slate-400 hover:text-white transition-colors"
                    >
                        <span className="material-symbols-outlined">close</span>
                    </button>
                </div>

                <div className="space-y-4">
                    {/* Edit Mode Toggle */}
                    <div className="flex items-center justify-between p-3 bg-white/5 rounded-lg border border-white/5">
                        <div className="flex items-center gap-3">
                            <span className="material-symbols-outlined text-slate-400">edit</span>
                            <span className="text-slate-200 font-medium">Bearbeitungsmodus</span>
                        </div>
                        <button
                            onClick={onToggleEditing}
                            className={`relative w-12 h-6 rounded-full transition-colors duration-300 ${isEditing ? 'bg-slate-200' : 'bg-slate-600'
                                }`}
                        >
                            <div
                                className={`absolute top-1 left-1 w-4 h-4 bg-white rounded-full transition-transform duration-300 ${isEditing ? 'translate-x-6' : 'translate-x-0'
                                    }`}
                            />
                        </button>
                    </div>

                    <div className="h-px bg-white/10 my-4" />

                    {/* Actions */}
                    <div className="space-y-2">
                        <button
                            onClick={onImport}
                            className="w-full flex items-center gap-3 p-3 bg-white/5 hover:bg-white/10 rounded-lg text-slate-200 transition-colors text-left"
                        >
                            <span className="material-symbols-outlined text-slate-400">upload</span>
                            <span>Konfiguration importieren</span>
                        </button>

                        <button
                            onClick={onExport}
                            className="w-full flex items-center gap-3 p-3 bg-white/5 hover:bg-white/10 rounded-lg text-slate-200 transition-colors text-left"
                        >
                            <span className="material-symbols-outlined text-slate-400">download</span>
                            <span>Konfiguration exportieren</span>
                        </button>

                        <button
                            onClick={onShowCredits}
                            className="w-full flex items-center gap-3 p-3 bg-white/5 hover:bg-white/10 rounded-lg text-slate-200 transition-colors text-left"
                        >
                            <span className="material-symbols-outlined text-slate-400">info</span>
                            <span>Credits anzeigen</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};
